### ISSUE TITLE
Переделки

### ISSUE THREAD

**Issue by ssnech** [andboson/fs.ua#10]
Добрый вечер, Андрей. Как ни странно, последних 2 дня все ссылки запускаются нормально...Но вот, новый прикол, - в некоторых папках в избранном не отображаются все файлы...например, в сериале "Сонная лощина" в папке 2-го сезона, отображается только первая серия сезона (Lostfilm), а остальных 17-ти серий нет, хотя на компе в этой же папке отображаются все 18 файлов. И другие есть такие же примеры. Что за чудеса? Как это исправить? Хотел зайти через поиск проверить...-так он не работает...
Спасибо за терпение, Андрей.

**Comment by andboson** [comment]
Добрый вечр.
Займусь не раньше субботы этим вопросом. Попрошу жену пока собрать какую-то статистику.

ЗЫ: вообще, сайт обещал АПИ, но когда - не ясно. Как оно появится - будет все стабильнее и проще

**Comment by andboson** [comment]
поправил
